### ISSUE TITLE
[BUG] generate fromTemplate fails since 1.13.0

### ISSUE THREAD

**Issue by eshepelyuk** [asyncapi/cli#1425]
### Describe the bug.

I am using CLI `generate fromTemplate` subcommand like this

```sh
asyncapi generate fromTemplate asyncapi.yaml @asyncapi/html-template --debug \
  -o build/docs -p singleFile=true -p version=1.1.1
```

And started to receive following error after upgrade to 1.13.0, also fails in 1.14.0.

```sh
(node:99804) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
┌  AsyncAPI Generator

/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/node-fetch/lib/index.js:1327
                throw new TypeError('Only absolute URLs are supported');
        ^
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/node-fetch/lib/index.js:1327:9)
    at /home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/node-fetch/lib/index.js:1450:19
    at new Promise (<anonymous>)
    at fetch (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/node-fetch/lib/index.js:1447:9)
    at Template.<anonymous> (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/lib/commands/generate/fromTemplate.js:194:61)
    at Generator.next (<anonymous>)
    at /home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/tslib/tslib.js:111:16)
    at Template.registryValidation (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/lib/commands/generate/fromTemplate.js:193:24)
    at Template.parseFlags (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/lib/commands/generate/fromTemplate.js:180:42)
    at Template.<anonymous> (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/lib/commands/generate/fromTemplate.js:88:38)
    at Generator.next (<anonymous>)
    at fulfilled (/home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error: Recipe `docs` failed with exit code 1
```

### Expected behavior

Docs generated successfully.

### Screenshots

![image](https://github.com/asyncapi/cli/assets/1279477/b8625d74-9cb4-4ee4-9457-fce03784dc01)

### How to Reproduce

Use 1.13.0 / 1.14.0 with command 

```sh
asyncapi generate fromTemplate asyncapi.yaml @asyncapi/html-template --debug \
  -o build/docs -p singleFile=true -p version=1.1.1
```

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by LoicBoursin** [comment]
I can confirm the exact same issue

**Comment by Amzani** [comment]
It might be related to https://github.com/asyncapi/cli/pull/1399
cc @AayushSaini101

**Comment by AayushSaini101** [comment]
> ```shell
> /home/linuxbrew/.linuxbrew/Cellar/asyncapi/1.14.0/libexec/lib/node_modules/@asyncapi/cli/node_modules/node-fetch/lib/index.js:1327
>                 throw new TypeError('Only absolute URLs are supported');
> ```

Checking @Amzani
